### ISSUE TITLE
Error theme.apply

### ISSUE THREAD

**Issue by Reyets** [bentx/vscode-custom-theme#1]
![vscode_csscustom_error](https://cloud.githubusercontent.com/assets/18214309/21160395/f9bab422-c184-11e6-99bd-f7ef3e5c423b.png)

I'm on Windows 10 Anniversary Update (14393.479), running VS Code Insider 1.8.0

(VS Code launched as Administrator)

**Comment by Reyets** [comment]
It works on my VS Code 1.6.1 with no extensions (maybe conflict?)

**Comment by bentx** [comment]
Interesting, I haven't tested it against Insider, will look into it !

**Comment by bentx** [comment]
Added support for Insiders and published new update, thanks for reporting
