### ISSUE TITLE
Can't change color of statusbar in Insiders on W10

### ISSUE THREAD

**Issue by jmn** [bentx/vscode-custom-theme#11]
Hi, I tried these settings and applied them but only the two later settings: smiley and font size become applied, the statusbar is still ill blue.
```
   "theme.statusbar.background.color": "#2c2c2c",
    "theme.statusbar.smiley.enabled": false,
    "theme.statusbar.font.size": "14px",
```

**Comment by bentx** [comment]
Curious, just tried your settings and all 3 applied for me, might me something new in Insiders. Will spin up a W10 VM and check on fresh Insiders install.

**Comment by bentx** [comment]
After installing the latest Insiders version, it looks like the vscode team already started integrating their own theming API, see this snippet from latest source as example :

```js
export const STATUS_BAR_BACKGROUND = registerColor('statusBarBackground', {
	dark: '#007ACC',
	light: '#007ACC',
	hc: null
}, nls.localize('statusBarBackground', "Standard status bar background color. The status bar is shown in the bottom of the window"));
```

Meaning this extension will soon be deprecated when they release this. I will stop supporting Insiders for now as they are likely to change many things during development.
