### ISSUE TITLE
Running the contributed command:'theme.apply' failed.

### ISSUE THREAD

**Issue by skube** [bentx/vscode-custom-theme#12]
I seem to get the above while trying to run `Custom Theme: Apply` on macOS 10.12.3

Is there a way to troubleshoot?

**Comment by bentx** [comment]
Sure, are you running on regular vscode or Insiders ? It seems like the latest Insiders version has breaking changes, I'll have to look into it.

**Comment by skube** [comment]
I believe I'm running the regular VSC

Version 1.10.2 (1.10.2)
8076a19fdcab7e1fc1707952d652f0bb6c6db331

**Comment by bentx** [comment]
Sounds like permission issue, I'm running the same version and everything works ok. But I'm also running on OS X 10.12.3, and there is nothing special to do regarding permissions. Could you have an antivirus or something like that preventing file writing ? 

If not, could you clone the extension and run it in debug mode in vscode ? The console would log events and show you what's failing when trying to apply the theme.

**Comment by skube** [comment]
Yes it was a permissions issue. 👍 

I simply changed owner and it worked: 
`sudo chown -R skube /Applications/Visual\ Studio\ Code.app`

**Comment by iamgp** [comment]
FWIW, I get the same error - reapplying user permissions didn't help.

**Comment by bentx** [comment]
@iamgp Same OS, same vscode version ? If yes could you try the debug option I mentioned in my previous message ?

**Comment by iamgp** [comment]
@bentx Yep same OS/version. Could you link me/describe how to do the debug option, please? I've literally just downloaded VSCode so know very little about it!

**Comment by bentx** [comment]
Sure, just `git clone` the repository, open it in new editor window, then go to the debug tab and run `launch extension`. This will open a new editor window with the extension running in it, there you can try to add some settings and apply the theme with `theme.apply`, if it fails, you can go back to your main window and check the debug console to see what error it prints, and post it here.

**Comment by iamgp** [comment]
Hi @bentx. I get the following error:

`Error: EROFS: read-only file system, open '/private/var/folders/50/80vnrrzs2cq0w4vpnq_5vrcw0000gn/T/AppTranslocation/6D99EA6A-125D-46A4-9A97-D22123322A25/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.css'`

**Comment by bentx** [comment]
Alright, that's the issue, thanks for the debug log. The path specified here includes `AppTranslocation`, meaning OSX mounted a read-only volume and copied the content of vscode inside of it before running, this behavior happens when you launch the app directly from your `~/Downloads` directory or any other location without really installing the app in `Applications`. 

This extension is patching vscode files and hence cannot be used that way, you will have to install the app properly (drag & drop into `Applications` directory) and then everything should work correctly, since the read-only volume is the problem here.

Let me know if it works for you that way.

**Comment by bentx** [comment]
I will close this issue as the vscode team released a new version and they now have theming support, meaning this extension is deprecated, see [this link](https://github.com/Microsoft/vscode/issues/1884#issuecomment-290940262).
