### ISSUE TITLE
Change statusbar icon color

### ISSUE THREAD

**Issue by gnhuy91** [bentx/vscode-custom-theme#3]
I have successfully changed my status bar background & text color, but there is no option to change icon colors (git, error counts...)

![image](https://cloud.githubusercontent.com/assets/10569203/21739696/0555ff18-d4d5-11e6-91f1-66745adc490c.png)

Great extension btw!

**Comment by bentx** [comment]
Added support for this in 1.0.9

**Comment by bentx** [comment]
Note: 1.0.9 introduced some minor issues, fixed in 1.1.1
