### ISSUE TITLE
Update for VSCode 1.9

### ISSUE THREAD

**Issue by gnhuy91** [bentx/vscode-custom-theme#5]
<img width="269" alt="screen shot 2017-02-03 at 1 14 44 pm" src="https://cloud.githubusercontent.com/assets/10569203/22581476/e021fbc2-ea12-11e6-8170-ba415b8a1aa2.png">

This is ver 1.9's TypeScript version switching.

**Comment by bentx** [comment]
Will look into it, thanks

**Comment by bentx** [comment]
Added support for this in 1.1.2
