### ISSUE TITLE
VSCode custom theme is not changing parameters.

### ISSUE THREAD

**Issue by aplsms** [bentx/vscode-custom-theme#6]
I can't change color of the status bar: looks like VSCode is ignoring my settings for theme.* 
VScode Version 1.9.0 (1.9.0)
Plugin Version 1.1.2
<img width="1842" alt="image" src="https://cloud.githubusercontent.com/assets/2309682/22766636/8059e110-ee2b-11e6-9ea7-471a37c8a44e.png">

**Comment by bentx** [comment]
Your settings look correct to me, did you run the "Custom theme : Apply" command ?

**Comment by aplsms** [comment]
my bad, sorry.
it works now.
