### ISSUE TITLE
Extension does nothing

### ISSUE THREAD

**Issue by fasa123** [bentx/vscode-custom-theme#9]
I am running on Linux, have one theme and no other extensions installed. When I add     

"theme.statusbar.background.color": "#fff",
    "theme.tabs.font.size": "20px" 

to the settings.json then save and call the command Apply custom themes the window refreshes but nothing changes. I did chown -r the files at /opt/VSCode-OSS and the user running vscode is the owner of that path. I get no output, no error message nothing just the page refreshing.

**Comment by bentx** [comment]
Will spin up a VM and look into it.

**Comment by bentx** [comment]
Working as expected on a fresh Fedora install, steps followed :
- install vscode
- sudo chown -R $(whoami) /usr/share/code
- add user setting entries for integrity check, smiley face and statusbar background color
- apply 
- no more smiley face, statusbar color changed

Please make sure you have correct permissions on /usr/share/code where vscode is installed, also, "theme.statusbar.background.color" is only for project mode, make sure you also have your color change for raw mode with "theme.statusbar.backgroundRaw.color".

**Comment by fasa123** [comment]
Yea I did all that. As said the owner of the vscode path is the user running vscode. I reinstalled it (including wiping ~/.vscode and ~/.Config/VSCode) and reran chown -R username /opt/VSCode but still I get the page refresh with nothing else happnening. That's pretty astonishing. Other addons modifing content from the /opt/VSCode folder work fine (and I do get the "Unsupported" message if I use those but not with this addon). Really strange. Regardless thanks for your time. I'll eventually try it on another machine but for whatever reason it does not work on my workstation. For the moment I'll take this as a fault on my part (or my machines) as thus I'll close it.

**Comment by bentx** [comment]
Hmmm. Would you mind cloning the repo and launching the extension through the debugger ? By doing so the debug console would tell you exactly what's wrong or at least we could narrow down the issue by using breakpoints (the extension code is fairly small ~150 lines). If you don't have time for that it's fine, but ideally I'd like to cover most machines including yours.

**Comment by fasa123** [comment]
I debugged the extension. The extension code executes all without any error. When the call to reload is finished and the extensions own code is finished the slave instance of vscode just crashes. The host shows me this https://i.imgur.com/uTVXyQh.png (yes I have set the configuration values in the global settings.json)

**Comment by bentx** [comment]
Which distro are you running on ? Arch ? Judging by the paths the debug output shows, would you have https://aur.archlinux.org/packages/visual-studio-code-oss/ installed instead of https://aur.archlinux.org/packages/visual-studio-code/ ? Or how did you install vscode ?

**Comment by fasa123** [comment]
Both correct. I am running Arch and using a self compiled OSS

**Comment by bentx** [comment]
Took me a bit of time to get that Arch VM running, steps followed on a fresh install :

- sudo pacman -Sy yaourt
- yaourt -S visual-studio-code
- sudo chown -R $(whoami) /opt/visual-studio-code
- add user setting entries for integrity check, smiley face and statusbar background color
- apply 
- no more smiley face, statusbar color changed

Unfortunately I couldn't install https://aur.archlinux.org/packages/visual-studio-code-oss/ since `yaourt -S visual-studio-code-oss` failed to build, but it seems to be working with the "official" package. 

I guess it means this "oss" package is different enough that it uses different paths for the assets, or something alike. Care to share why using this package over the other one ?

**Comment by fasa123** [comment]
Mind me not replying have been busy with exams.

https://aur.archlinux.org/packages/visual-studio-code/ this package is a commercial branded package by Microsoft which to me personally is reason enough not to use it. Also seeing some packages published by Microsoft just ignore the telemetry settings it is highly likely that vscode (the commercial package) does it as well. That would also explain why you only get a "true OSS" variant if you exclude the extension gallery from the build process.

**Comment by bentx** [comment]
I see, thanks for taking time to explain. Interesting fact about the telemetry settings, if it's true it's pretty bad practice indeed.

Hope you did well with your exams !
